#ifndef AOFLAGGER_VERSION_H
#define AOFLAGGER_VERSION_H

#define AOFLAGGER_VERSION_STR      "2.4.1"
#define AOFLAGGER_VERSION_MAJOR    2
#define AOFLAGGER_VERSION_MINOR    4
#define AOFLAGGER_VERSION_SUBMINOR 1
#define AOFLAGGER_VERSION_DATE_STR "2013-04-28"

#endif
