#ifndef AOFLAGGER_VERSION_H
#define AOFLAGGER_VERSION_H

#define AOFLAGGER_VERSION_STR      "2.5.0"
#define AOFLAGGER_VERSION_MAJOR    2
#define AOFLAGGER_VERSION_MINOR    5
#define AOFLAGGER_VERSION_SUBMINOR 0
#define AOFLAGGER_VERSION_DATE_STR "2013-08-24"

#endif
